import { baseApi } from './baseApi';

export { baseApi, baseApi as apiSlice } from './baseApi';
export default baseApi;


// Import injected feature APIs
import {
  authApi,
  useRegisterMutation,
  useLoginMutation,
  useRefreshTokenMutation,
  useLogoutApiMutation,
  useVerifyEmailMutation,
  useResendVerificationMutation,
  useForgotPasswordMutation,
  useResetPasswordMutation,
} from '../../features/auth/authApi';

import {
  userApi,
  useGetMeQuery,
  useLazyGetMeQuery,
  useGetUserByIdQuery,
  useSearchUsersQuery,
  useUpdateUserMutation,
  useUploadProfileImageMutation,
  useUpdatePasswordMutation,
} from '../../features/users/userApi';

import {
  postApi,
  useGetPostsQuery,
  useLazyGetPostsQuery,
  useGetPostByIdQuery,
  useGetAnswersQuery,
  useCreatePostMutation,
  useCreatePostWithImagesMutation,
  useCreateAnswerMutation,
  useUpdatePostMutation,
  useDeletePostMutation,
  useGetPostsByViewsQuery,
  useGetPostsByScoreQuery,
  useSearchPostsQuery,
  useLazySearchPostsQuery,
  useSearchPostsRelevanceQuery,
  useGetPostsByTagQuery,
  useGetPostsByUserQuery,
  useGetQuestionsQuery,
  useLazyGetQuestionsQuery,
  useGetQuestionByIdQuery,
  useCreateQuestionMutation,
  useAddAnswerMutation,
  useAcceptAnswerMutation,
} from '../../features/posts/postApi';

import {
  commentApi,
  useGetCommentsByPostQuery,
  useGetCommentsByUserQuery,
  useCreateCommentMutation,
  useUpdateCommentMutation,
  useDeleteCommentMutation,
  useAddCommentMutation,
} from '../../features/comments/commentApi';

import {
  voteApi,
  useVotePostMutation,
  useUpdateVoteMutation,
  useDeleteVoteMutation,
  useVoteQuestionMutation,
  useVoteAnswerMutation,
} from '../../features/votes/voteApi';

import {
  tagApi,
  useGetTagsQuery,
  useGetPopularTagsQuery,
  useGetTopTagsQuery,
  useSearchTagsQuery,
} from '../../features/tags/tagApi';

import {
  lostFoundApi,
  useGetReportsQuery,
  useLazyGetReportsQuery,
  useGetReportByIdQuery,
  useCreateReportMutation,
  useGetCategoriesQuery,
  useCreateCategoryMutation,
  useGetLocationsQuery,
  useCreateLocationMutation,
  useGetClaimsQuery,
  useCreateClaimMutation,
  useApproveClaimMutation,
  useRejectClaimMutation,
  useGetMatchesQuery,
  useUpdateMatchStatusMutation,
  useDeleteReportMutation,
  useUpdateReportMutation,
  useGetLostFoundItemsQuery,
  useLazyGetLostFoundItemsQuery,
  useGetLostFoundItemByIdQuery,
  useCreateItemMutation,
  useDeleteItemMutation,
  useUpdateItemStatusMutation,
} from '../../features/lostFound/lostFoundApi';

import {
  bookmarkApi,
  useGetBookmarksQuery,
  useAddBookmarkMutation,
  useRemoveBookmarkMutation,
} from '../../features/bookmarks/bookmarkApi';

import {
  notificationApi,
  useGetNotificationsQuery,
  useGetUnreadCountQuery,
  useMarkReadMutation,
  useMarkAllReadMutation,
  useMarkNotificationAsReadMutation,
  useMarkAllNotificationsAsReadMutation,
  useMarkNotificationReadMutation,
  useMarkAllNotificationsReadMutation,
  useDeleteNotificationMutation,
} from '../../features/notifications/notificationApi';

import {
  uploadApi,
  useUploadSingleMutation,
  useUploadMultipleMutation,
} from '../../features/upload/uploadApi';

import {
  leaderboardApi,
  useGetLeaderboardQuery,
} from '../../features/leaderboard/leaderboardApi';

import {
  achievementsApi,
  useGetAchievementsQuery,
} from '../../features/achievements/achievementsApi';

import {
  adminApi,
  useGetAdminAnalyticsQuery,
  useGetUsersQuery,
  useUpdateUserRoleMutation,
  useToggleBlockUserMutation,
  useUpdateClaimStatusMutation,
  useUpdateReportStatusMutation,
} from '../../features/admin/adminApi';

// Re-export all hooks and endpoints
export const useGetItemByIdQuery = useGetReportByIdQuery;

export {
  authApi,
  useRegisterMutation,
  useLoginMutation,
  useRefreshTokenMutation,
  useLogoutApiMutation,
  useVerifyEmailMutation,
  useResendVerificationMutation,
  useForgotPasswordMutation,
  useResetPasswordMutation,
  userApi,
  useGetMeQuery,
  useLazyGetMeQuery,
  useGetUserByIdQuery,
  useSearchUsersQuery,
  useUpdateUserMutation,
  useUploadProfileImageMutation,
  useUpdatePasswordMutation,
  postApi,
  useGetPostsQuery,
  useLazyGetPostsQuery,
  useGetPostByIdQuery,
  useGetAnswersQuery,
  useCreatePostMutation,
  useCreatePostWithImagesMutation,
  useCreateAnswerMutation,
  useUpdatePostMutation,
  useDeletePostMutation,
  useGetPostsByViewsQuery,
  useGetPostsByScoreQuery,
  useSearchPostsQuery,
  useLazySearchPostsQuery,
  useSearchPostsRelevanceQuery,
  useGetPostsByTagQuery,
  useGetPostsByUserQuery,
  useGetQuestionsQuery,
  useLazyGetQuestionsQuery,
  useGetQuestionByIdQuery,
  useCreateQuestionMutation,
  useAddAnswerMutation,
  useAcceptAnswerMutation,
  commentApi,
  useGetCommentsByPostQuery,
  useGetCommentsByUserQuery,
  useCreateCommentMutation,
  useUpdateCommentMutation,
  useDeleteCommentMutation,
  useAddCommentMutation,
  voteApi,
  useVotePostMutation,
  useUpdateVoteMutation,
  useDeleteVoteMutation,
  useVoteQuestionMutation,
  useVoteAnswerMutation,
  tagApi,
  useGetTagsQuery,
  useGetPopularTagsQuery,
  useGetTopTagsQuery,
  useSearchTagsQuery,
  lostFoundApi,
  useGetReportsQuery,
  useLazyGetReportsQuery,
  useGetReportByIdQuery,
  useCreateReportMutation,
  useGetCategoriesQuery,
  useCreateCategoryMutation,
  useGetLocationsQuery,
  useCreateLocationMutation,
  useGetClaimsQuery,
  useCreateClaimMutation,
  useApproveClaimMutation,
  useRejectClaimMutation,
  useGetMatchesQuery,
  useUpdateMatchStatusMutation,
  useDeleteReportMutation,
  useUpdateReportMutation,
  useGetLostFoundItemsQuery,
  useLazyGetLostFoundItemsQuery,
  useGetLostFoundItemByIdQuery,
  useCreateItemMutation,
  useDeleteItemMutation,
  useUpdateItemStatusMutation,
  bookmarkApi,
  useGetBookmarksQuery,
  useAddBookmarkMutation,
  useRemoveBookmarkMutation,
  notificationApi,
  useGetNotificationsQuery,
  useGetUnreadCountQuery,
  useMarkReadMutation,
  useMarkAllReadMutation,
  useMarkNotificationAsReadMutation,
  useMarkAllNotificationsAsReadMutation,
  useMarkNotificationReadMutation,
  useMarkAllNotificationsReadMutation,
  useDeleteNotificationMutation,
  uploadApi,
  useUploadSingleMutation,
  useUploadMultipleMutation,
  leaderboardApi,
  useGetLeaderboardQuery,
  achievementsApi,
  useGetAchievementsQuery,
  adminApi,
  useGetAdminAnalyticsQuery,
  useGetUsersQuery,
  useUpdateUserRoleMutation,
  useToggleBlockUserMutation,
  useUpdateClaimStatusMutation,
  useUpdateReportStatusMutation,
};
